# https://taskfile.dev

version: "3"

vars:
  Version: 4.0
  Build: 1
  Tag: v{{.Version}}.{{.Build}}

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  push-tag:
    cmds:
      - echo {{.Tag}}
      - git tag -a "{{.Tag}}" -m "{{.Tag}}"
      - git push origin "{{.Tag}}"
